# Positive x is right, positive y is down
# Tile grid is based on top left of tiles

GAME_NAME = "22 Seconds"
WIDTH, HEIGHT = 1280, 720
TILE_SIZE = 80

DAY_LENGTH = 90 # Seconds
DUSK_DAWN_LENGTH = 10 # Seconds
NIGHT_LENGTH = 22 # Seconds

TARGET_RADIUS = TILE_SIZE * 3 # Pixels

# Map stuff
MAP_WIDTH = 50
MAP_HEIGHT = 30

MAP_UPDATE_RATE = 600
PARTICLES_PER_TILE_SECOND = 5
RANDOM_TICK_PER_UPDATE_RATIO = 0.01

# Graphical stuff
NIGHT_OPACITY = 150

CROSSHAIR_ONLY_WITH_JOYSTICK = True
CROSSHAIR_SIZE = 10
CROSSHAIR_COLOR = (255, 255, 255)
CROSSHAIR_THICKNESS = 2